tools:
  external_code_coverage: true
checks:
  php:
    code_rating: true
    duplication: true
filter:
  paths:
  - src/*
build:
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
