language: php

php:
  - 7.1
  - 7.2

addons:
  hosts:
    - awesome.scot

sudo: false

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install

before_script:
  - export DISPLAY=:99.0
  - export PATH=$PATH:vendor/bin
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - mysql -e "create database IF NOT EXISTS oauth2api;\n" -uroot
  - mysql -e "USE mysql;\n" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO dbuser@'%' IDENTIFIED BY '[123456]';\n" -uroot
  - mysql -e "FLUSH PRIVILEGES;\n" -uroot
  - migrant migrate --no-interaction
  - migrant generate-proxies
  - nohup php -S awesome.scot:8000 public/index.php &
script:
  - php vendor/bin/codecept run api --env travis -vvv
after_script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
