language: php

php:
  - 7.1
  - 7.2

addons:
  hosts:
    - awesome.scot

sudo: true

before_install:
  - sudo apt-get install -y golang-go
  - sudo apt-get install -y stunnel
  - go get github.com/mailhog/MailHog
  - go get github.com/mailhog/mhsendmail
  - sudo cp /home/travis/gopath/bin/MailHog /usr/local/bin/mailhog
  - sudo cp /home/travis/gopath/bin/mhsendmail /usr/local/bin/mhsendmail
install:
  - mailhog -api-bind-addr 127.0.0.1:8025 -ui-bind-addr 127.0.0.1:8025 -smtp-bind-addr 127.0.0.1:1025 &
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install

before_script:
  - export DISPLAY=:99.0
  - export PATH=$PATH:vendor/bin
  - export APPLICATION_ENV=travis
  - cp data/keys/private.key.sample data/keys/private.key
  - cp data/keys/public.key.sample data/keys/public.key
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - mysql -e "create database IF NOT EXISTS oauth2api;\n" -uroot
  - mysql -e "USE mysql;\n" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO dbuser@'%' IDENTIFIED BY '[123456]';\n" -uroot
  - mysql -e "FLUSH PRIVILEGES;\n" -uroot
  - migrant migrate --no-interaction
  - migrant generate-proxies data/proxies
  - nohup php -S awesome.scot:8000 public/index.php &
  - stunnel3 -d 443 -r 8000
script:
  - php vendor/bin/codecept run --env travis --coverage-xml -vvv
after_script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
after_failure:
  - cat /home/travis/build/delboy1978uk/oauth2-api/data/logs/error_log

notifications:
  irc: "irc.freenode.org#bonemvc"
