version: '2'

volumes:
    db_data:
        driver: local

services:
    awesome.scot:
        build: ./build/httpd
        links:
            - php
        ports:
            - 80:80
            - 443:443
        volumes_from:
            - app

    php:
        build: ./build/php
        ports:
            - 9000
            - 9001
        volumes_from:
            - app
        links:
            - mariadb
            - mail
        environment:
            APPLICATION_ENV: 'development'

    app:
        image: httpd:latest
        volumes:
            - ./:/var/www/html
        command: "echo true"

    mariadb:
        image: mariadb:latest
        volumes:
            - ./build/data:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '[123456]'
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: '[123456]'
        ports:
            - 3306:3306

    mail:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
